[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
BinaryBuilder = "12aac903-9f7c-5d81-afc2-d9565ea332ae"
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
GLPK = "60bf3e95-4087-53dc-ae20-288a0d20c6a6"
HiGHS = "87dc4568-4c63-4d18-b0c0-bb2238e4078b"
Jasmin = "933bf34c-63a6-4b3c-9215-9e95b90b8e7c"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"
RDST = "dc077566-edc2-11e8-0ce0-7d758bb9a5d1"
RNGTest = "97cc5700-e6cb-5ca1-8fb2-7f6b45264ecd"
StochasticPrograms = "8b8459f2-c380-502b-8633-9aed2d6c2b35"

[compat]
julia = "1.7"
